Workaround so that docx4all via JNLP/Java Web Start can use Java 6 JAXB, rather than also needing JAXB RI.
JAXB in Java 6 has problems doing stuff (when invoked via JNLP) that the JAXB RI can do.  Specifically:

java.security.AccessControlException: access denied (java.lang.RuntimePermission accessDeclaredMembers)
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkMemberAccess(Unknown Source)
	at java.lang.Class.checkMemberAccess(Unknown Source)
	at java.lang.Class.getDeclaredField(Unknown Source)

The JNLP file grants all-permissions (and the applet is signed ). 

http://java.sun.com/javase/6/docs/technotes/guides/jweb/tools/security.html says: ".. trusted code will be granted the AllPermission permission"

But AllPermission is not all permissions (accessDeclaredMembers)???

So instead we do System.setSecurityManager(null)

(Possibly because we extend com.sun.xml.internal.bind.marshaller.NamespacePrefixMapper ?)